# Generated by Django 4.2 on 2023-06-06 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_address_line_2_order_floor_and_more'),
        ('carts', '0005_remove_cartitem_variations'),
        ('store', '0004_alter_product_id_alter_reviewrating_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='product',
        ),
        migrations.DeleteModel(
            name='ReviewRating',
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
